Models/UpdatePassword.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AKStore.Models
{
    public class UpdatePassword
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Old Password is required")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Old Password is required")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [MinLength(6,ErrorMessage = "Password length must be more than 6 character")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "New Password is required")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "New Password is required")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Confirm Password is required")]
        [RegularExpression(@"^.*\S.*$", ErrorMessage = "Confirm Password is required")]
        [Compare("NewPassword", ErrorMessage = "Confirm Password is not matching with new password")]
        public string ConfirmPassword { get; set; }
    }
}

Controllers/CommonController.cs
using AKStore.Extension;
using AKStore.Filters;
using AKStore.Models;
using AKStore.Services;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AKStore.Controllers
{
    public class CommonController : Controller
    {
        private readonly IUserService _userService;
        private readonly IProductService productService;
        private readonly IDistributorService distributorService;
        public CommonController()
        {
            _userService = new UserService();
            distributorService = new DistributorService();
            productService = new ProductService();
        }
        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        [HttpPost]
        public ActionResult SetDefualtPassword(string userName)
        {
            _userService.SetDefualtPassword(userName);
            return Redirect(Request.UrlReferrer.OriginalString);
        }

        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        public ActionResult UserDetails()
        {
            int userId = Convert.ToInt32(Session["LoggedInUserId"]);
            var usersModel = _userService.GetUsersById(userId);
            return View(usersModel);
        }

        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        [HttpGet]
        public ActionResult UpdatePassword()
        {

            return View();
        }
        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        [HttpPost]
        public ActionResult UpdatePassword(UpdatePassword updatePassword)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(UpdatePassword), updatePassword);
            }
            if (string.IsNullOrEmpty(updatePassword.NewPassword.Trim()) ||
                string.IsNullOrEmpty(updatePassword.OldPassword.Trim()) ||
                string.IsNullOrEmpty(updatePassword.ConfirmPassword.Trim())
                 )
            {
                ModelState.AddModelError("", "Please enter all fields");
                return View(nameof(UpdatePassword), updatePassword);
            }
            int userId = Convert.ToInt32(Session["LoggedInUserId"]);

            var isPasswordUpdated = _userService.UpdatePassword(updatePassword, userId);
            if (isPasswordUpdated == 1)
            {
                return RedirectToAction(nameof(UserDetails));
            }
            else
            {
                ModelState.AddModelError("", "Old password is not correct");
                return View(nameof(UpdatePassword), updatePassword);
            }


        }
        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        [HttpGet]
        public ActionResult UpdateProfile()
        {
            int userId = Convert.ToInt32(Session["LoggedInUserId"]);
            var usersModel = _userService.GetUsersById(userId);
            UpdateProfileModel updateProfileModel = new UpdateProfileModel()
            {
                FirstName = usersModel.FirstName,
                LastName = usersModel.LastName,
                Address = usersModel.Address,
                PostalCode = usersModel.PostalCode,
                PhNo1 = usersModel.PhNo1,
                PhNo2 = usersModel.PhNo2
            };
            return View(updateProfileModel);

        }
        [CustomAuthorize(Role.SuperAdmin, Role.Admin, Role.Distributor, Role.Customer)]
        [HttpPost]
        public ActionResult UpdateProfile(UpdateProfileModel updateProfileModel)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(UpdateProfile), updateProfileModel);
            }
            int userId = Convert.ToInt32(Session["LoggedInUserId"]);
            var isProfileUpdated = _userService.UpdateProfile(updateProfileModel, userId);
            if (isProfileUpdated == 1)
            {
                return RedirectToAction(nameof(UserDetails));
            }
            else
            {
                return View(nameof(UpdateProfile), updateProfileModel);
            }


        }

        [CustomAuthorize(Role.Distributor, Role.Customer, Role.Admin)]
        public ActionResult DashBoard()
        {
            return View();
        }
        [CustomAuthorize(Role.Distributor, Role.Customer, Role.Admin)]
        public ActionResult DashBoardData(DateTime fromDate, DateTime toDate, int orderStatusId, int customerId)
        {

            //cutomerId = Convert.ToInt32(Session["CustomerId"]);
            int distributorId = distributorService.FirstDistributor().Id;
            // int distributorId = Convert.ToInt32(Session["DistributorId"]);
            var desData = _userService.GetDashBoardData(fromDate, toDate, orderStatusId, customerId, distributorId);
            var jsonstr = JsonConvert.SerializeObject(desData, Formatting.Indented);
            return Json(new { data = jsonstr, Success = true }, JsonRequestBehavior.AllowGet);
        }
      
        [AllowCrossSiteJson]
        public ActionResult GetProducts()
        {
            try
            {
                var products = productService.GetProduct(1);
                return Json(new { data = products, Success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { data = new List<ProductModel>(), Success = false, Error = ex.Message }, JsonRequestBehavior.AllowGet);
            }

        }

    }
}

Views/Common/DashBoard.cshtml

@{
    ViewBag.Title = "DashBoard";
}
<div class="card shadow-lg">
    <div class="card-header">
        <h6 class="m-0 font-weight-bold text-primary">DashBoard</h6>
    </div>
    <div class="card-body">
        <div class="form-horizontal">
            <div class="row">
                @if (Convert.ToInt32(Session["RoleId"]) != 6)
                {
                    <div class="col-12 col-md-4">
                        <label>Customer</label>
                        <select id="drpCustomers" class="form-control" onchange="GetDashboardData()">
                        </select>
                    </div>
                }
                <div class="col-12 col-md-3" style="display:none">
                    <label style="text-align:center">Order Status</label>
                    <select id="drpOrderStatus" class="form-control" onchange="GetDashboardData()">
                        <option value="1">Ordered</option>
                        <option value="0">All</option>
                        <option value="2">Confirmed</option>
                        <option value="3" selected>Delivered</option>
                        <option value="4">Canceled</option>
                    </select>
                </div>
                <div class="col-12 col-md-4">
                    <label for="saleDate" style="display:block">From Date</label>
                    <input type="text" id="FromDate" class="form-control datepicker" style="background-color: white;" readonly />
                </div>
                <div class="col-12 col-md-4">
                    <label for="saleDate" style="display:block">To Date</label>
                    <input type="text" id="ToDate" class="form-control datepicker" style="background-color:white;" readonly />
                </div>
                <br />
                <br />
                <br />
                <br />

                <div class="col-12 col-md-6 mt-3">
                    <div class="card shadow-sm">
                        <div class="card-header">
                            <h6 class="m-0 font-weight-bold text-primary">Product</h6>
                        </div>
                        <div class="card-body table-responsive border" id="divProduct">

                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-6 mt-3" id="divCustomerParent">
                    <div class="card shadow-sm">
                        <div class="card-header">
                            <h6 class="m-0 font-weight-bold text-primary">Customer</h6>
                        </div>
                        <div class="card-body table-responsive border" id="divCustomer">

                        </div>
                    </div>
                </div>
                <br />
                <div class="col-12 col-md-6 mt-3">
                    <div class="card shadow-sm">
                        <div class="card-header">
                            <h6 class="m-0 font-weight-bold text-primary">Transaction</h6>
                        </div>
                        <div class="card-body table-responsive border" id="divTransaction">

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        var roleId = '@Convert.ToInt32(Session["RoleId"])';
        $(document).ready(function () {
            ConfigureDate();
            if (roleId != 6) {
                GetCustomers();
            } else {
                GetDashboardData();
            }
          
        })
        function ConfigureDate() {
            var today = new Date();
            var previoisMonthDate = new Date(new Date().getFullYear(), new Date().getMonth() - 1, new Date().getDate());

            $("#FromDate").datepicker({

                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat: 'dd/mm/yy',
                maxDate: today
            });

            $("#FromDate").datepicker("setDate", previoisMonthDate)
                .on("change", function () {
                    GetDashboardData();
                });
            $("#ToDate").datepicker({

                showOtherMonths: true,
                selectOtherMonths: true,
                changeMonth: true,
                changeYear: true,
                dateFormat: 'dd/mm/yy',
                maxDate: today

            })
            $("#ToDate").datepicker("setDate", today)
                .on("change", function () {
                    GetDashboardData();
                });
        }
        function GetCustomers() {
            $.ajax({
                type: "GET",
                url: '@Url.Action("GetCustomerData", "Customer")',
                success: function (response) {
                    if (response.Success) {

                        var htmlRoute = "<option value=" + 0 + ">--All--</option>";
                        response.Data.filter(function (item) {
                            htmlRoute += GenrateDropDown(item.Id, item.StoreName);
                        });
                        $("#drpCustomers").html(htmlRoute);
                        GetDashboardData();
                    }
                },
                error: function (error) {
                    alert(error);
                }
            });
        }
        function GetDashboardData() {
            var customerId = (roleId!=6? $("#drpCustomers").val():'@Convert.ToInt32(Session["CustomerId"])');
            var orderStatusId = $("#drpOrderStatus").val();
            var fromDate = ConvertDateToDDMMYY($("#FromDate").val());
            var toDate = ConvertDateToDDMMYY($("#ToDate").val());
            var postData = {
                customerId: customerId,
                orderStatusId: orderStatusId,
                fromDate: fromDate,
                toDate: toDate
            };
            $.ajax({
                type: "GET",
                url: '@Url.Action("DashBoardData", "Common")',
                data: postData,
                success: function (response) {
                    if (response.Success) {
                        console.log(JSON.parse(response.data));
                       /* BindOrdersGrid(response);*/
                        BindProductsReportGrid(JSON.parse(response.data).Table1);
                        if (roleId != 6) {
                            BindCustomerReportGrid(JSON.parse(response.data).Table2);
                        } else {
                            $("#divCustomerParent").hide();
                        }
                        
                        BindTransactionReportGrid(JSON.parse(response.data).Table3);
                    }
                    else {
                        toastr.error(response.Message);
                    }
                },
                error: function (error) {
                    alert(error);
                }
            });
        }
        function BindProductsReportGrid(response) {
            var strHtml = `<table class="table table-bordered" id="tblProductReport">
                                    <thead class="success">
                                        <tr>
                                            <th>Product</th>
                                            <th>Qty</th>
                                        </tr>
                                    </thead>`;
            response.forEach(function (item) {
                strHtml += `<tr>
                                    <td>
                                        <div class="product-photo" style="background-image:url('/Documents/images/product/${item.FilePath ?? "NoImage.png"}')" ></div>
                                        <div class="product-name">${item.ProductName}</div>
                                     </td>
                                    <td>${item.Quantity}</td>
                               </tr>`;
            });
            strHtml += `</table>`;
            $("#divProduct").html(strHtml);
            $('#tblProductReport').addClass("table-striped");
            $('#tblProductReport').DataTable({
                "pageLength": 5,
                order: [1, 'desc'],
            });
        }
        function BindCustomerReportGrid(response) {
            var strHtml = `<table class="table table-bordered" id="tblCustomerReport">
                                    <thead class="success">
                                        <tr>
                                            <th>Store Name</th>
                                            <th>Product</th>
                                            <th>Qty</th>
                                        </tr>
                                    </thead>`;
            response.forEach(function (item) {
                strHtml += `<tr>
                                    <td>
                                        ${item.StoreName}
                                     </td>
                                       <td>
                                        <div class="product-photo" style="background-image:url('/Documents/images/product/${item.FilePath ?? "NoImage.png"}')" ></div>
                                        <div class="product-name">${item.ProductName}</div>
                                     </td>
                                    <td>${item.Quantity}</td>
                               </tr>`;
            });
            strHtml += `</table>`;
            $("#divCustomer").html(strHtml);
            $('#tblCustomerReport').addClass("table-striped");
            $('#tblCustomerReport').DataTable({
                "pageLength": 5,
                order: [2, 'desc'],
            });
        }
        function BindTransactionReportGrid(response) {
            var strHtml = `<table class="table table-bordered" id="tblTransactionReport">
                                    <thead class="success">
                                        <tr>
                                            <th>Customer</th>
                                            <th>Openning Amount</th>
                                            <th>Purchased Amount</th>
                                            <th>Paid Amount</th>
                                            <th>OutStanding</th>
                                        </tr>
                                    </thead>`;
            response.forEach(function (item) {
                strHtml += `<tr>
                                    <td>
                                        ${item.StoreName}
                                     </td>
                                      <td>
                                        ${item.OpenningBalance}
                                     </td>
                                      <td>
                                        ${item.PurchasedAmount}
                                     </td>
                                       <td>
                                        ${item.PaidAmount}
                                     </td>
                                      <td>
                                        ${item.OutStanding}
                                     </td>


                               </tr>`;
            });
            strHtml += `</table>`;
            $("#divTransaction").html(strHtml);
            $('#tblTransactionReport').addClass("table-striped");
            $('#tblTransactionReport').DataTable({
                "pageLength": 5,
                order: [4, 'desc'],
            });
        }
    </script>
}

Views/Common/UpdatePassword.cshtml
@model AKStore.Models.UpdatePassword

@{
    ViewBag.Title = "Update Password";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">Update Password</h6>
            </div>
            <div class="card-body">

                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="form-group">
                                @Html.Label("Old Password", htmlAttributes: new { @class = "mb-1" })

                                @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="form-group">
                                @Html.Label("New Password", htmlAttributes: new { @class = "mb-1" })

                                @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="form-group">
                                @Html.Label("Confirm Password", htmlAttributes: new { @class = "mb-1" })

                                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })

                            </div>
                        </div>
                        <div class="col-12">
                            <div class="form-group">
                                <input type="submit" value="Save" class="btn btn-grad" />
                                <a href='@Url.Action("UserDetails")' class="btn  btn-secondary ">Back to Profile</a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

</div>

Views/Common/UpdateProfile.cshtml
@model AKStore.Models.UpdateProfileModel

@{
    ViewBag.Title = "Update Profile";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow">
            <div class="card-header">
                <h6 class="m-0 font-weight-bold text-primary">Update Profile</h6>
            </div>
            <div class="card-body">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                <div class="row">

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="col-12 col-md-6">
                        @Html.LabelFor(model => model.FirstName)
                        @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })

                    </div>
                    <div class="col-12 col-md-6">
                        @Html.LabelFor(model => model.LastName)
                        @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })

                    </div>
                    <div class="col-12 col-md-6">
                        @Html.Label("PhNo 1")
                        @Html.EditorFor(model => model.PhNo1, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhNo1, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-12 col-md-6">
                        @Html.Label("PhNo 2")
                        @Html.EditorFor(model => model.PhNo2, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PhNo2, "", new { @class = "text-danger" })
                    </div>

                    <div class="col-12 col-md-12">
                        @Html.LabelFor(model => model.Address)
                        @Html.TextAreaFor(model => model.Address, new { @class = "form-control", rows = "4" })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>


                    <div class="col-12">
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-grad" />
                            <a href='@Url.Action("UserDetails")' class="btn  btn-secondary ">Back to Profile</a>
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>

</div>


Views/Common/UserDetails.cshtml
@model AKStore.Models.UsersModel

@{
    ViewBag.Title = "Profile";
}


<div class="container" style="margin:0px;padding:0px;">

    <div class="row">
        <div class="col-12 ">
            <div class="card shadow">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">Profile</h6>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-6 col-sm-6 small">
                            <a href="@Url.Action("UpdateProfile","Common")">Update Profile</a>
                        </div>
                        <div class="col-6 col-sm-6 small">
                            <a href="@Url.Action("UpdatePassword","Common")">Update Password</a>
                        </div>
                    </div>
                    <hr />
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered border">
                            <tbody>
                                <tr>
                                    <th>@Html.LabelFor(Model => Model.UserName, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td> @Html.DisplayFor(model => model.UserName)</td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td> @Html.DisplayFor(model => model.FirstName)</td>
                                </tr> 
                                <tr>
                                    <th>@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td> @Html.DisplayFor(model => model.LastName)</td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(model => model.PhNo1, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td> @Html.DisplayFor(model => model.PhNo1)</td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(model => model.PhNo2, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td> @Html.DisplayFor(model => model.PhNo2)</td>
                                </tr>
                                <tr>
                                    <th>@Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "font-weight-bold" })</th>
                                    <td>@Html.DisplayFor(model => model.Address)</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>